/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;

/**
 *
 * @author silve
 */
public class inicio extends javax.swing.JFrame {

    public static login frmLogin;
    public static registro frmReg;
    
    
    public inicio() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnFormLogin = new javax.swing.JButton();
        btnFormReg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 255, 153));
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(118, 170, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFormLogin.setBackground(new java.awt.Color(204, 204, 255));
        btnFormLogin.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btnFormLogin.setText("Inicia Sesion");
        btnFormLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnFormLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 26, 270, 80));

        btnFormReg.setBackground(new java.awt.Color(204, 204, 255));
        btnFormReg.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btnFormReg.setText("Registrarse");
        btnFormReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnFormReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 270, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mundoa2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormLoginActionPerformed
        // TODO add your handling code here:\
        
        if (frmLogin == null){
        
            frmLogin = new login();
            frmLogin.setVisible(true);
        }
    }//GEN-LAST:event_btnFormLoginActionPerformed

    private void btnFormRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormRegActionPerformed
        
        if (frmReg == null){
        
            frmReg = new registro();
            frmReg.setVisible(true);
        
        }
        
        
    }//GEN-LAST:event_btnFormRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormLogin;
    private javax.swing.JButton btnFormReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
