/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.*;
import modelo.Hash;
import modelo.SqlUsuarios;
import modelo.Usuarios;

public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRegUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRegPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRegPassConfirm = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtRegNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRegApellido = new javax.swing.JTextField();
        txtRegCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        btnRegSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(118, 183, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("REGISTRO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        txtRegUsuario.setBackground(new java.awt.Color(204, 204, 255));
        txtRegUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRegUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtRegUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 142, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        txtRegPass.setBackground(new java.awt.Color(204, 204, 255));
        txtRegPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtRegPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 142, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Confirmar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        txtRegPassConfirm.setBackground(new java.awt.Color(204, 204, 255));
        txtRegPassConfirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtRegPassConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 142, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        txtRegNombre.setBackground(new java.awt.Color(204, 204, 255));
        txtRegNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRegNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtRegNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtRegNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 142, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Apellido:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        txtRegApellido.setBackground(new java.awt.Color(204, 204, 255));
        txtRegApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRegApellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtRegApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 142, -1));

        txtRegCorreo.setBackground(new java.awt.Color(204, 204, 255));
        txtRegCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRegCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtRegCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 142, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Correo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        btnRegistro.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistro.setText("Registrar");
        btnRegistro.setToolTipText("");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 130, 46));

        btnRegSalir.setBackground(new java.awt.Color(153, 153, 255));
        btnRegSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegSalir.setText("Salir");
        btnRegSalir.setToolTipText("");
        btnRegSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 130, 46));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro4.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegSalirActionPerformed

        JOptionPane.showMessageDialog(null, "Saliendo...");
        System.exit(0);


    }//GEN-LAST:event_btnRegSalirActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed

        SqlUsuarios modSQL = new SqlUsuarios();
        Usuarios mod = new Usuarios();

        String pass = new String(txtRegPass.getPassword());
        String passCon = new String(txtRegPassConfirm.getPassword());

        if (txtRegUsuario.getText().equals("") || pass.equals("") || txtRegNombre.getText().equals("") || txtRegApellido.getText().equals("") || txtRegCorreo.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos");
        } else {

            if (pass.equals(passCon)) {

                if (modSQL.validarUsuarioExistente(txtRegUsuario.getText()) == 0) {

                    if (modSQL.validarEmail(txtRegCorreo.getText())) {

                        String nuevoPass = Hash.sha1(pass);

                        mod.setUsuario(txtRegUsuario.getText());
                        mod.setPass(nuevoPass);
                        mod.setNombre(txtRegNombre.getText());
                        mod.setApellido(txtRegApellido.getText());
                        mod.setCorreo(txtRegCorreo.getText());
                        mod.setId_tipo(1);

                        if (modSQL.registrar(mod)) {
                            JOptionPane.showMessageDialog(null, "Registro guardado");
                            limpiarBtn();

                        } else {
                            JOptionPane.showMessageDialog(null, "Error al realizar el registro :(");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Error! Ese no es un correo valido");

                    }

                } else {

                    JOptionPane.showMessageDialog(null, "Error! Este usuario ya existe!");
                }

            } else {

                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden!");
            }

        }

    }//GEN-LAST:event_btnRegistroActionPerformed

    private void limpiarBtn() {

        txtRegUsuario.setText("");
        txtRegPass.setText("");
        txtRegPassConfirm.setText("");
        txtRegNombre.setText("");
        txtRegApellido.setText("");
        txtRegCorreo.setText("");

    }


    private void txtRegNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegNombreActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        inicio.frmReg = null;

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegSalir;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtRegApellido;
    private javax.swing.JTextField txtRegCorreo;
    private javax.swing.JTextField txtRegNombre;
    private javax.swing.JPasswordField txtRegPass;
    private javax.swing.JPasswordField txtRegPassConfirm;
    private javax.swing.JTextField txtRegUsuario;
    // End of variables declaration//GEN-END:variables
}
